-- sin^2 theta
-- wrong: the exponentiation operator cannot be applied to functions
--
-- sin theta^2
-- correct: same as (sin(theta))^2
--
-- (sin theta)^2
-- correct: function application has the highest precedence
